# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anaekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(701, 533)
        MainWindow.setStyleSheet("background-color: rgb(255, 235, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.paymentlbl = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paymentlbl.sizePolicy().hasHeightForWidth())
        self.paymentlbl.setSizePolicy(sizePolicy)
        self.paymentlbl.setStyleSheet("background-color: rgb(255, 235, 255);\n"
"border : 2px solid rgb(85, 0, 0);\n"
"font:14pt \"Britannic Bold\";\n"
"color : rgb(85, 0, 0);\n"
"\n"
"")
        self.paymentlbl.setObjectName("paymentlbl")
        self.gridLayout.addWidget(self.paymentlbl, 3, 2, 1, 1)
        self.dateVL = QtWidgets.QVBoxLayout()
        self.dateVL.setObjectName("dateVL")
        self.datelbl = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datelbl.sizePolicy().hasHeightForWidth())
        self.datelbl.setSizePolicy(sizePolicy)
        self.datelbl.setStyleSheet("background-color: rgb(255, 235, 255);\n"
"border : 2px solid rgb(85, 0, 0);\n"
"font:14pt \"Britannic Bold\";\n"
"color : rgb(85, 0, 0);\n"
"\n"
"")
        self.datelbl.setObjectName("datelbl")
        self.dateVL.addWidget(self.datelbl)
        self.gridLayout.addLayout(self.dateVL, 0, 2, 1, 1)
        self.tasklbl = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tasklbl.sizePolicy().hasHeightForWidth())
        self.tasklbl.setSizePolicy(sizePolicy)
        self.tasklbl.setStyleSheet("background-color: rgb(255, 235, 255);\n"
"border : 2px solid rgb(85, 0, 0);\n"
"font:14pt \"Britannic Bold\";\n"
"color : rgb(85, 0, 0);\n"
"\n"
"")
        self.tasklbl.setObjectName("tasklbl")
        self.gridLayout.addWidget(self.tasklbl, 1, 2, 1, 1)
        self.calenderVL = QtWidgets.QVBoxLayout()
        self.calenderVL.setObjectName("calenderVL")
        self.calenderlbl = QtWidgets.QCalendarWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calenderlbl.sizePolicy().hasHeightForWidth())
        self.calenderlbl.setSizePolicy(sizePolicy)
        self.calenderlbl.setStyleSheet("\n"
"font:8pt \"Britannic Bold\";\n"
"color : rgb(85, 0, 0);\n"
"background-color: rgb(255, 235, 255);\n"
"border : 1px solid rgb(85, 0, 0);\n"
"")
        self.calenderlbl.setObjectName("calenderlbl")
        self.calenderVL.addWidget(self.calenderlbl)
        self.gridLayout.addLayout(self.calenderVL, 0, 0, 3, 2)
        self.notelbl = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notelbl.sizePolicy().hasHeightForWidth())
        self.notelbl.setSizePolicy(sizePolicy)
        self.notelbl.setStyleSheet("background-color: rgb(255, 235, 255);\n"
"border : 2px solid rgb(85, 0, 0);\n"
"font:14pt \"Britannic Bold\";\n"
"color : rgb(85, 0, 0);\n"
"\n"
"\n"
"")
        self.notelbl.setObjectName("notelbl")
        self.gridLayout.addWidget(self.notelbl, 3, 1, 1, 1)
        self.butVL = QtWidgets.QVBoxLayout()
        self.butVL.setObjectName("butVL")
        self.taskBut = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskBut.sizePolicy().hasHeightForWidth())
        self.taskBut.setSizePolicy(sizePolicy)
        self.taskBut.setStyleSheet("color : rgb(85, 0, 0);\n"
"font: 87 italic 10pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 235, 255);\n"
"border : 2px solid rgb(85, 0, 0);")
        self.taskBut.setObjectName("taskBut")
        self.butVL.addWidget(self.taskBut)
        self.paymentBut = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paymentBut.sizePolicy().hasHeightForWidth())
        self.paymentBut.setSizePolicy(sizePolicy)
        self.paymentBut.setStyleSheet("color : rgb(85, 0, 0);\n"
"font: 87 italic 10pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 235, 255);\n"
"border : 2px solid rgb(85, 0, 0);")
        self.paymentBut.setObjectName("paymentBut")
        self.butVL.addWidget(self.paymentBut)
        self.noteBut = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noteBut.sizePolicy().hasHeightForWidth())
        self.noteBut.setSizePolicy(sizePolicy)
        self.noteBut.setStyleSheet("color : rgb(85, 0, 0);\n"
"font: 87 italic 10pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 235, 255);\n"
"border : 2px solid rgb(85, 0, 0);")
        self.noteBut.setObjectName("noteBut")
        self.butVL.addWidget(self.noteBut)
        self.gridLayout.addLayout(self.butVL, 3, 0, 3, 1)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setStyleSheet("background-color: rgb(255, 235, 255);\n"
"font: 87 8pt \"Arial Black\";\n"
"border : 2px solid rgb(85, 0, 0);\n"
"\n"
"")
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 4, 1, 2, 1)
        self.listWidget_3 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_3.setStyleSheet("background-color: rgb(255, 235, 255);\n"
"font: 87 8pt \"Arial Black\";\n"
"border : 2px solid rgb(85, 0, 0);\n"
"\n"
"")
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout.addWidget(self.listWidget_3, 2, 2, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setStyleSheet("background-color: rgb(255, 235, 255);\n"
"font: 87 8pt \"Arial Black\";\n"
"border : 2px solid rgb(85, 0, 0);\n"
"\n"
"")
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout.addWidget(self.listWidget_2, 4, 2, 2, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 701, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TASK TRACK"))
        self.paymentlbl.setText(_translate("MainWindow", "Ödemeleriniz"))
        self.datelbl.setText(_translate("MainWindow", "TARİH : GG/AA/YYYY"))
        self.tasklbl.setText(_translate("MainWindow", "Görevleriniz"))
        self.notelbl.setText(_translate("MainWindow", "Notlarınız"))
        self.taskBut.setText(_translate("MainWindow", "Görev Ekle"))
        self.paymentBut.setText(_translate("MainWindow", "Ödeme Ekle"))
        self.noteBut.setText(_translate("MainWindow", "Not Ekle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
